#!/bin/bash

# asdf
# https://asdf-vm.com/
if [ ! -d "$HOME/.asdf" ]; then
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf
fi

cd ~/.asdf
git pull
git checkout "$(git describe --abbrev=0 --tags)"

# Dependencies for languages
sudo apt install automake autoconf libreadline-dev libncurses-dev libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev -y

# Ruby
# https://github.com/asdf-vm/asdf-ruby
bash ~/.asdf/bin/asdf plugin-add ruby

# Nodejs
# https://github.com/asdf-vm/asdf-nodejs
bash ~/.asdf/bin/asdf plugin-add nodejs
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

# Erlang
# https://github.com/asdf-vm/asdf-erlang
bash ~/.asdf/bin/asdf plugin-add erlang

# Elixir
# https://github.com/asdf-vm/asdf-elixir
bash ~/.asdf/bin/asdf plugin-add elixir

# Rust
# https://github.com/code-lever/asdf-rust
bash ~/.asdf/bin/asdf plugin-add rust

# Go
# https://github.com/kennyp/asdf-golang
bash ~/.asdf/bin/asdf plugin-add golang
