#!/bin/zsh

# asdf
# https://asdf-vm.com/
if [ ! -d "$HOME/.asdf" ]; then
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf
fi

cd ~/.asdf
git pull
git checkout "$(git describe --abbrev=0 --tags)"

# Dependencies for languages
sudo apt install automake autoconf libreadline-dev libncurses-dev libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev -y

# Ruby
# https://github.com/asdf-vm/asdf-ruby
bash ~/.asdf/bin/asdf plugin-add ruby

# Nodejs
# https://github.com/asdf-vm/asdf-nodejs
bash ~/.asdf/bin/asdf plugin-add nodejs
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

# Yarn
# https://github.com/twuni/asdf-yarn
bash ~/.asdf/bin/asdf plugin-add yarn

# Erlang
# https://github.com/asdf-vm/asdf-erlang
bash ~/.asdf/bin/asdf plugin-add erlang
sudo apt-get install -y build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk

# Elixir
# https://github.com/asdf-vm/asdf-elixir
bash ~/.asdf/bin/asdf plugin-add elixir
sudo apt-get install -y unzip

# Rust
# https://github.com/code-lever/asdf-rust
bash ~/.asdf/bin/asdf plugin-add rust

# Go
# https://github.com/kennyp/asdf-golang
bash ~/.asdf/bin/asdf plugin-add golang

# PHP
# https://github.com/asdf-community/asdf-php
bash ~/.asdf/bin/asdf plugin-add php
sudo apt-get install -y bison libcurl4-gnutls-dev libpq-dev libzip-dev
