#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

# Linux only. On macOS, the Brewfile installs b2-tools.
[[ "$(uname)" == Linux ]] || { echo "Skip: Linux only"; exit 0; }

# B2 command-line too
# https://www.backblaze.com/b2/docs/quick_command_line.html
sudo curl -L https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux -o /usr/local/bin/b2
sudo chmod +x /usr/local/bin/b2
