#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

sudo apt install -y  \
  apt-transport-https \
   ca-certificates \
   curl \
   software-properties-common

sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt update
sudo apt install -y docker-ce docker-ce-cli

sudo groupadd docker
sudo usermod -aG docker $USER

mkdir -p $HOME/.docker/cli-plugins
sudo curl -L https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-`uname -s`-`uname -m` -o $HOME/.docker/cli-plugins/docker-compose
sudo chmod +x $HOME/.docker/cli-plugins/docker-compose

# Completion
# curl -L https://raw.githubusercontent.com/docker/compose/v2.17.3/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose
