#!/bin/bash

# Flatpak packages:
# - https://obsidian.md/
flatpak install obsidian

# Simple animated GIF screen recorder with an easy to use interface
# https://github.com/phw/peek
flatpak install flathub com.uploadedlobster.peek

# Required by peek to run via app icon
sudo apt install -y xdg-desktop-portal-gtk
