#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

# Add source
# 🚧 Replace by manual installation
# git clone https://github.com/sobolevn/git-secret.git git-secret
# cd git-secret && make build
# requires sudo:
# PREFIX="/usr/local" make install

sudo curl -fsSL https://gitsecret.jfrog.io/artifactory/api/gpg/key/public | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/gitsecret.gpg

echo "deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main" | sudo tee -a /etc/apt/sources.list
sudo apt-get update

# git-secret
# https://git-secret.io
sudo apt-get install git-secret
