#!/bin/bash

# Add source
echo "deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main" | sudo tee -a /etc/apt/sources.list
wget -qO - https://gitsecret.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -
sudo apt-get update

# git-secret
# https://git-secret.io
sudo apt-get install git-secret
