#!/bin/bash

LOGSEQ_VSN=0.1.3

# Logseq
# https://github.com/logseq/logseq
# sudo curl -L https://github.com/logseq/logseq/releases/download/$LOGSEQ_VSN/logseq-linux-x64-$LOGSEQ_VSN.AppImage -o /usr/local/bin/logseq
# sudo chmod +x /usr/local/bin/logseq

# Add a shortcut
touch $HOME/.local/share/applications/logseq.desktop
cat <<EOT > $HOME/.local/share/applications/logseq.desktop
[Desktop Entry]
Name=Logseq
Exec=/usr/local/bin/logseq
Terminal=false
Type=Application
EOT

