#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

[[ "$(uname)" == Linux ]] || { echo "Skip: Linux only"; exit 0; }

# Mattermost desktop
# https://mattermost.com
sudo apt install -y mattermost-desktop
