#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

# Linux only. On macOS, the Brewfile installs mosh.
[[ "$(uname)" == Linux ]] || { echo "Skip: Linux only"; exit 0; }

# Mobile shell that supports roaming and intelligent local echo
# https://mosh.org/
sudo apt install -y mosh
