#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

sudo apt install python3-pip -y

# Ansible
# https://www.ansible.com/
pip3 install ansible

# Borgmatic
# https://torsion.org/borgmatic/
pip3 install borgmatic

# S3CMD
# https://s3tools.org/s3cmd
pip3 install s3cmd

# Gigalixir
# https://gigalixir.readthedocs.io/en/latest/getting-started-guide.html
pip3 install gigalixir

# httpie
# https://httpie.io/
pip3 install httpie
