#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

# Snap
sudo apt install -y snapd

# [Snap packages](https://snapcraft.io)
# - Emote - A Modern popup emoji picker
# - doctl - The official DigitalOcean command line interface
sudo snap install emote drawio spotify doctl
