#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

# Add source
sudo curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/sublimehq-pub.gpg

echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update

# SublimeText
# https://www.sublimetext.com/
sudo apt install sublime-text -y


# SublimeMerge
# https://www.sublimemerge.com/
sudo apt install sublime-merge -y
