#!/bin/bash

# Add source
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update

# SublimeText
# https://www.sublimetext.com/
sudo apt install sublime-text -y


# SublimeMerge
# https://www.sublimemerge.com/
sudo apt install sublime-merge -y
