#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

# tmux
# https://github.com/tmux/tmux

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

# On macOS the Brewfile installs tmux
if [[ "$(uname)" == Linux ]]; then
  sudo apt install -y tmux
fi
