#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

# Linux only. On macOS, the Brewfile installs topgrade.
[[ "$(uname)" == Linux ]] || { echo "Skip: Linux only"; exit 0; }

topgrade_vsn=17.9.0

# Topgrade - Upgrade everything
# https://github.com/topgrade-rs/topgrade
cd `mktemp -d`
curl -L https://github.com/topgrade-rs/topgrade/releases/download/v${topgrade_vsn}/topgrade-v${topgrade_vsn}-x86_64-unknown-linux-musl.tar.gz -o topgrade.tar.gz
tar -xvf topgrade.tar.gz
sudo mv -f topgrade /usr/local/bin/topgrade
sudo chmod +x /usr/local/bin/topgrade
