#!/bin/zsh

set -o errexit
set -o nounset
set -o pipefail

[[ "$(uname)" == Linux ]] || { echo "Skip: Linux only"; exit 0; }

# VirtualBox
# https://www.virtualbox.org/
# Vagrant
# https://www.vagrantup.com/
sudo apt install -y virtualbox vagrant
