#!/bin/bash

# Update Pop!_OS
sudo apt update && sudo apt full-upgrade -y

function install {
  which $1 &> /dev/null

  if [ $? -ne 0 ]; then
    echo "Installing: ${1}..."
    sudo apt install -y $1
  else
    echo "Already installed: ${1}"
  fi
}

# Install basic dependencies
install apache2-utils
install apt-transport-https
install borgbackup
install ffmpeg
install imagemagick
install inotify-tools
install libnotify-bin
install nautilus-dropbox
install network-manager-openvpn-gnome
install parallel
install ubuntu-restricted-extras
install zsh

# Run all programs/ install scripts
for f in scripts/programs/*; do ./$f; done

# Create folders
mkdir -p ~/.workspace
